---
- name: Update apt cache
  apt:
    update_cache: yes
- name: Install Apache
  apt:
    name: apache2
    state: present
- name: Copy index test page
  template:
    src: "files/index.html"
    dest: "/var/www/html/index.html"
- name: Start Apache
  service:
    name: apache2
    state: started
    enabled: yes
